security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    acl:
        connection: default

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, SONATA]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT # if you are not using acl then this line must be uncommented
            - ROLE_SONATA_PAGE_ADMIN_BLOCK_EDIT

    providers:
        main:
            id: fos_user.user_provider.username
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
                    pattern: ^/(_(profiler|wdt)|css|images|js)/
                    security: false
        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
            logout:
                path:           /admin/logout
                target:         /admin/login
            anonymous:          true
        main:
            pattern:      ^/
            anonymous:    true
            provider:     main
            form_login:
              default_target_path: /
              login_path: fos_user_security_login
              check_path: fos_user_security_check
            logout:
              path:       fos_user_security_logout
              target:     /
              handlers: ['sonata.page.cms_manager_selector']

    access_control:
          #- { path: ^/admin, ip: 127.0.0.1, requires_channel: https }
          # Admin login page needs to be accessed without credential
          - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

          # Secured part of the site
          # This config requires being logged for the whole site and having the admin role for the admin part.
          # Change these rules to adapt them to your needs
          - { path: ^/admin/, role: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_ADMIN, ROLE_SONATA_ADMIN] }
          - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
