imports:
    - { resource: sonata_block.yml }
    - { resource: sonata_doctrine_orm_admin.yml }
    - { resource: sonata_admin.yml }
    - { resource: sonata_user.yml}

sonata_core:
    form:
        mapping:
            enabled: false


sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb