<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.page.block.breadcrumb' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\block-bundle\\src\\Block\\BlockServiceInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\block-bundle\\src\\Block\\Service\\BlockServiceInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\block-bundle\\src\\Block\\Service\\AbstractBlockService.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\block-bundle\\src\\Block\\Service\\AdminBlockServiceInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\block-bundle\\src\\Block\\Service\\AbstractAdminBlockService.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\block-bundle\\src\\Block\\Service\\MenuBlockService.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\seo-bundle\\src\\Block\\Breadcrumb\\BaseBreadcrumbMenuBlockService.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\Block\\BreadcrumbBlockService.php';

return $this->services['sonata.page.block.breadcrumb'] = new \Sonata\PageBundle\Block\BreadcrumbBlockService('page', 'sonata.page.block.breadcrumb', ${($_ = isset($this->services['sonata.templating']) ? $this->services['sonata.templating'] : $this->getSonata_TemplatingService()) && false ?: '_'}, ${($_ = isset($this->services['knp_menu.menu_provider']) ? $this->services['knp_menu.menu_provider'] : $this->getKnpMenu_MenuProviderService()) && false ?: '_'}, ${($_ = isset($this->services['knp_menu.factory']) ? $this->services['knp_menu.factory'] : $this->load('getKnpMenu_FactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['sonata.page.cms_manager_selector']) ? $this->services['sonata.page.cms_manager_selector'] : $this->services['sonata.page.cms_manager_selector'] = new \Sonata\PageBundle\CmsManager\CmsManagerSelector($this)) && false ?: '_'});
