<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.page.kernel.exception_listener' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\Listener\\ExceptionListener.php';

return $this->services['sonata.page.kernel.exception_listener'] = new \Sonata\PageBundle\Listener\ExceptionListener(${($_ = isset($this->services['sonata.page.site.selector.host']) ? $this->services['sonata.page.site.selector.host'] : $this->getSonata_Page_Site_Selector_HostService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.page.cms_manager_selector']) ? $this->services['sonata.page.cms_manager_selector'] : $this->services['sonata.page.cms_manager_selector'] = new \Sonata\PageBundle\CmsManager\CmsManagerSelector($this)) && false ?: '_'}, true, ${($_ = isset($this->services['sonata.templating']) ? $this->services['sonata.templating'] : $this->getSonata_TemplatingService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.page.page_service_manager']) ? $this->services['sonata.page.page_service_manager'] : $this->getSonata_Page_PageServiceManagerService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.page.decorator_strategy']) ? $this->services['sonata.page.decorator_strategy'] : $this->getSonata_Page_DecoratorStrategyService()) && false ?: '_'}, array(404 => '_page_internal_error_not_found', 500 => '_page_internal_error_fatal'), ${($_ = isset($this->services['monolog.logger.request']) ? $this->services['monolog.logger.request'] : $this->getMonolog_Logger_RequestService()) && false ?: '_'});
