<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.page.manager.block' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\block-bundle\\src\\Model\\BlockManagerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\Entity\\BlockManager.php';

return $this->services['sonata.page.manager.block'] = new \Sonata\PageBundle\Entity\BlockManager('Application\\Sonata\\PageBundle\\Entity\\Block', ${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
