<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.page.block_interactor' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\Model\\BlockInteractorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\Entity\\BlockInteractor.php';

return $this->services['sonata.page.block_interactor'] = new \Sonata\PageBundle\Entity\BlockInteractor(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.page.manager.block']) ? $this->services['sonata.page.manager.block'] : $this->load('getSonata_Page_Manager_BlockService.php')) && false ?: '_'});
