<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.page.transformer' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\Model\\TransformerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\Entity\\Transformer.php';

return $this->services['sonata.page.transformer'] = new \Sonata\PageBundle\Entity\Transformer(${($_ = isset($this->services['sonata.page.manager.snapshot']) ? $this->services['sonata.page.manager.snapshot'] : $this->load('getSonata_Page_Manager_SnapshotService.php')) && false ?: '_'}, ${($_ = isset($this->services['sonata.page.manager.page']) ? $this->services['sonata.page.manager.page'] : $this->load('getSonata_Page_Manager_PageService.php')) && false ?: '_'}, ${($_ = isset($this->services['sonata.page.manager.block']) ? $this->services['sonata.page.manager.block'] : $this->load('getSonata_Page_Manager_BlockService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
