<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.page.route.page.generator' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\Route\\RoutePageGenerator.php';

return $this->services['sonata.page.route.page.generator'] = new \Sonata\PageBundle\Route\RoutePageGenerator(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.page.manager.page']) ? $this->services['sonata.page.manager.page'] : $this->load('getSonata_Page_Manager_PageService.php')) && false ?: '_'}, ${($_ = isset($this->services['sonata.page.decorator_strategy']) ? $this->services['sonata.page.decorator_strategy'] : $this->getSonata_Page_DecoratorStrategyService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.page.kernel.exception_listener']) ? $this->services['sonata.page.kernel.exception_listener'] : $this->load('getSonata_Page_Kernel_ExceptionListenerService.php')) && false ?: '_'});
