<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.page.form.type.page_selector' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Form\\FormTypeInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Form\\AbstractType.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\Form\\Type\\PageSelectorType.php';

return $this->services['sonata.page.form.type.page_selector'] = new \Sonata\PageBundle\Form\Type\PageSelectorType(${($_ = isset($this->services['sonata.page.manager.page']) ? $this->services['sonata.page.manager.page'] : $this->load('getSonata_Page_Manager_PageService.php')) && false ?: '_'});
