<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sonata\NotificationBundle\Command\CreateAndPublishCommand' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Command\\Command.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Command\\ContainerAwareCommand.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\notification-bundle\\src\\Command\\CreateAndPublishCommand.php';

return $this->services['Sonata\NotificationBundle\Command\CreateAndPublishCommand'] = new \Sonata\NotificationBundle\Command\CreateAndPublishCommand();
