<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.page.proxy.snapshot.factory' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\Model\\SnapshotPageProxyFactoryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\Model\\SnapshotPageProxyFactory.php';

return $this->services['sonata.page.proxy.snapshot.factory'] = new \Sonata\PageBundle\Model\SnapshotPageProxyFactory('Sonata\\PageBundle\\Model\\SnapshotPageProxy');
