<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.page.validator.unique_url' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Validator\\ConstraintValidatorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Validator\\ConstraintValidator.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\Validator\\UniqueUrlValidator.php';

return $this->services['sonata.page.validator.unique_url'] = new \Sonata\PageBundle\Validator\UniqueUrlValidator(${($_ = isset($this->services['sonata.page.manager.page']) ? $this->services['sonata.page.manager.page'] : $this->load('getSonata_Page_Manager_PageService.php')) && false ?: '_'});
