<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.page.cms.snapshot' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\CmsManager\\CmsManagerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\CmsManager\\BaseCmsPageManager.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\CmsManager\\CmsSnapshotManager.php';

return $this->services['sonata.page.cms.snapshot'] = new \Sonata\PageBundle\CmsManager\CmsSnapshotManager(${($_ = isset($this->services['sonata.page.manager.snapshot']) ? $this->services['sonata.page.manager.snapshot'] : $this->load('getSonata_Page_Manager_SnapshotService.php')) && false ?: '_'}, ${($_ = isset($this->services['sonata.page.transformer']) ? $this->services['sonata.page.transformer'] : $this->load('getSonata_Page_TransformerService.php')) && false ?: '_'});
