<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.notification.backend.runtime' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\notification-bundle\\src\\Backend\\BackendInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\notification-bundle\\src\\Backend\\RuntimeBackend.php';

return $this->services['sonata.notification.backend.runtime'] = new \Sonata\NotificationBundle\Backend\RuntimeBackend(${($_ = isset($this->services['sonata.notification.dispatcher']) ? $this->services['sonata.notification.dispatcher'] : $this->load('getSonata_Notification_DispatcherService.php')) && false ?: '_'});
