<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.page.manager.page' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\Model\\PageManagerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\Entity\\PageManager.php';

return $this->services['sonata.page.manager.page'] = new \Sonata\PageBundle\Entity\PageManager('Application\\Sonata\\PageBundle\\Entity\\Page', ${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, array('templateCode' => 'default', 'enabled' => true, 'routeName' => NULL, 'name' => NULL, 'slug' => NULL, 'url' => NULL, 'requestMethod' => NULL, 'decorate' => true), array('homepage' => array('templateCode' => 'default', 'enabled' => true, 'routeName' => NULL, 'name' => NULL, 'slug' => NULL, 'url' => NULL, 'requestMethod' => NULL, 'decorate' => false)));
