<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.page.block.ajax' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\Controller\\AjaxController.php';

return $this->services['sonata.page.block.ajax'] = new \Sonata\PageBundle\Controller\AjaxController(${($_ = isset($this->services['sonata.page.cms_manager_selector']) ? $this->services['sonata.page.cms_manager_selector'] : $this->services['sonata.page.cms_manager_selector'] = new \Sonata\PageBundle\CmsManager\CmsManagerSelector($this)) && false ?: '_'}, ${($_ = isset($this->services['sonata.block.renderer.default']) ? $this->services['sonata.block.renderer.default'] : $this->getSonata_Block_Renderer_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.page.block.context_manager']) ? $this->services['sonata.page.block.context_manager'] : $this->getSonata_Page_Block_ContextManagerService()) && false ?: '_'});
