<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.page.router' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony-cmf\\routing\\src\\VersatileGeneratorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony-cmf\\routing\\src\\ChainedRouterInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\Route\\CmsPageRouter.php';

return $this->services['sonata.page.router'] = new \Sonata\PageBundle\Route\CmsPageRouter(${($_ = isset($this->services['sonata.page.cms_manager_selector']) ? $this->services['sonata.page.cms_manager_selector'] : $this->services['sonata.page.cms_manager_selector'] = new \Sonata\PageBundle\CmsManager\CmsManagerSelector($this)) && false ?: '_'}, ${($_ = isset($this->services['sonata.page.site.selector.host']) ? $this->services['sonata.page.site.selector.host'] : $this->getSonata_Page_Site_Selector_HostService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
