<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.page.cms.page' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\CmsManager\\CmsManagerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\CmsManager\\BaseCmsPageManager.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\CmsManager\\CmsPageManager.php';

return $this->services['sonata.page.cms.page'] = new \Sonata\PageBundle\CmsManager\CmsPageManager(${($_ = isset($this->services['sonata.page.manager.page']) ? $this->services['sonata.page.manager.page'] : $this->load('getSonata_Page_Manager_PageService.php')) && false ?: '_'}, ${($_ = isset($this->services['sonata.page.block_interactor']) ? $this->services['sonata.page.block_interactor'] : $this->load('getSonata_Page_BlockInteractorService.php')) && false ?: '_'});
