<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.page.notification.cleanup_snapshot' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\notification-bundle\\src\\Consumer\\ConsumerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\page-bundle\\src\\Consumer\\CleanupSnapshotConsumer.php';

return $this->services['sonata.page.notification.cleanup_snapshot'] = new \Sonata\PageBundle\Consumer\CleanupSnapshotConsumer(${($_ = isset($this->services['sonata.page.manager.snapshot']) ? $this->services['sonata.page.manager.snapshot'] : $this->load('getSonata_Page_Manager_SnapshotService.php')) && false ?: '_'}, ${($_ = isset($this->services['sonata.page.manager.page']) ? $this->services['sonata.page.manager.page'] : $this->load('getSonata_Page_Manager_PageService.php')) && false ?: '_'});
