<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.notification.consumer.logger' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\notification-bundle\\src\\Consumer\\ConsumerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\notification-bundle\\src\\Consumer\\LoggerConsumer.php';

return $this->services['sonata.notification.consumer.logger'] = new \Sonata\NotificationBundle\Consumer\LoggerConsumer(${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'});
