<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQdkdntu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQdkdntu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQdkdntu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQdkdntu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQdkdntu\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Qdkdntu',
    'container.build_id' => '535bf9bb',
    'container.build_time' => 1529578232,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQdkdntu');
